sonar.projectKey=Jhemder_AppEventsUPeU
sonar.organization=Jhemder

sonar.sources=lib
sonar.tests=test

sonar.sourceEncoding=UTF-8

sonar.flutter.coverage.reportPath=coverage/lcov.info

sonar.exclusions=**/*.g.dart,**/*.freezed.dart